### PR TITLE
Update greenlight client library

### PR DESCRIPTION
**Pull request by rdmitr**

### CODE REVIEW

**Comment by rolznz** [comment]
@rdmitr ~~this doesn't seem right to me. I think we can create credentials from the device key and cert.~~

Unfortunately they haven't updated their tutorial at https://blockstream.github.io/greenlight/getting-started/schedule/. I will ask them if they can update it or give us some sample code.

Also, for some reason I cannot run the examples any more (like get_info) - compilation fails. Do you have any idea why?

**Comment by rolznz** [comment]
@rdmitr actually maybe you are right.

For some reason I cannot recover the node though - I get:
```
{"level":"error","msg":"Failed to recover node: SdkError: GreenlightApi: greenlight API error: failed to recover credentials: status: Unknown, message: \"transport error\", details: [], metadata: MetadataMap { headers: {} }: transport error: connection error: unexpected end of file: unexpected end of file","time":"2024-03-26T21:53:04+07:00"}
```

**Comment by rolznz** [comment]
@rdmitr update: it seemed to recover on a following attempt, but it fails to do the get_info call.

I have asked Greenlight for help.

**Comment by rdmitr** [comment]
@rolznz have you tried cleaning the build dir? Did you run the get-info example directly? It seems to work for me 🤔

**Comment by rdmitr** [comment]
@rolznz I have updated the dependencies again, just in case. Also, which version of Rust do you use? I'm on 1.77.0.

**Comment by rolznz** [comment]
@rdmitr I'm on 1.76.0.

Thanks for updating the dependencies. I can now connect to my node and see my onchain balance and channels. But redeeming my onchain balance caused the node to hang. I have asked greenlight again

**Review by rolznz — APPROVED** [review]
tACK

**Pull request merged**
